[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "out"
  exclude = [
    '/api/**',
    '/success',
    '/checkout'
  ]
  prettyURLs = true